# Generated by Django 2.2.3 on 2019-07-08 17:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_coin', models.IntegerField(default=0)),
                ('qtd_coin_recebido', models.IntegerField(default=0)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(max_length=255, verbose_name='Mensagem :')),
                ('qtd_coin', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade easyCoin')),
                ('data_pub', models.DateField(auto_now_add=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_destino', to='feedback.Carteira', verbose_name='Destinatário :')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_remetente', to='feedback.Carteira')),
            ],
        ),
    ]
