# Generated by Django 2.0.13 on 2019-09-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='data_pub',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
