# Generated by Django 2.2.1 on 2019-05-31 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecargaCoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('qtd_coin_mes', models.IntegerField(default=15)),
                ('date_alter', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
