# Generated by Django 2.2.1 on 2019-06-04 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recargacoin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recargacoin',
            name='date_alter',
        ),
        migrations.RemoveField(
            model_name='recargacoin',
            name='dia',
        ),
    ]
